#include "gen2/Gen2Items.h"

const char* getGen2ItemString(Gen2Items item)
{
    switch (item)
    {
        case Gen2Items::UNKNOWN: return "Unknown";
        case Gen2Items::MASTER_BALL: return "Master Ball";
        case Gen2Items::ULTRA_BALL: return "Ultra Ball";
        case Gen2Items::BRIGHTPOWDER: return "Brightpowder";
        case Gen2Items::GREAT_BALL: return "Great Ball";
        case Gen2Items::POKE_BALL: return "Poke Ball";
        case Gen2Items::TERU_SAMA: return "Teru Sama";
        case Gen2Items::BICYCLE: return "Bicycle";
        case Gen2Items::MOON_STONE: return "Moon Stone";
        case Gen2Items::ANTIDOTE: return "Antidote";
        case Gen2Items::BURN_HEAL: return "Burn Heal";
        case Gen2Items::ICE_HEAL: return "Ice Heal";
        case Gen2Items::AWAKENING: return "Awakening";
        case Gen2Items::PARLYZ_HEAL: return "Parlyz Heal";
        case Gen2Items::FULL_RESTORE: return "Full Restore";
        case Gen2Items::MAX_POTION: return "Max Potion";
        case Gen2Items::HYPER_POTION: return "Hyper Potion";
        case Gen2Items::SUPER_POTION: return "Super Potion";
        case Gen2Items::POTION: return "Potion";
        case Gen2Items::ESCAPE_ROPE: return "Escape Rope";
        case Gen2Items::REPEL: return "Repel";
        case Gen2Items::MAX_ELIXER: return "Max Elixer";
        case Gen2Items::FIRE_STONE: return "Fire Stone";
        case Gen2Items::THUNDER_STONE: return "Thunder Stone";
        case Gen2Items::WATER_STONE: return "Water Stone";
        case Gen2Items::TERU_SAMA2: return "Teru Sama 2";
        case Gen2Items::HP_UP: return "HP Up";
        case Gen2Items::PROTEIN: return "Protein";
        case Gen2Items::IRON: return "Iron";
        case Gen2Items::CARBOS: return "Carbos";
        case Gen2Items::LUCKY_PUNCH: return "Lucky Punch";
        case Gen2Items::CALCIUM: return "Calcium";
        case Gen2Items::RARE_CANDY: return "Rare Candy";
        case Gen2Items::X_ACCURACY: return "X Accuracy";
        case Gen2Items::LEAF_STONE: return "Leaf Stone";
        case Gen2Items::METAL_POWDER: return "Metal Powder";
        case Gen2Items::NUGGET: return "Nugget";
        case Gen2Items::POKE_DOLL: return "Poke Doll";
        case Gen2Items::FULL_HEAL: return "Full Heal";
        case Gen2Items::REVIVE: return "Revive";
        case Gen2Items::MAX_REVIVE: return "Max Revive";
        case Gen2Items::GUARD_SPEC: return "Guard Spec";
        case Gen2Items::SUPER_REPEL: return "Super Repel";
        case Gen2Items::MAX_REPEL: return "Max Repel";
        case Gen2Items::DIRE_HIT: return "Dire Hit";
        case Gen2Items::TERU_SAMA3: return "Teru Sama 3";
        case Gen2Items::FRESH_WATER: return "Fresh Water";
        case Gen2Items::SODA_POP: return "Soda Pop";
        case Gen2Items::LEMONADE: return "Lemonade";
        case Gen2Items::X_ATTACK: return "X Attack";
        case Gen2Items::TERU_SAMA4: return "Teru Sama 4";
        case Gen2Items::X_DEFEND: return "X Defend";
        case Gen2Items::X_SPEED: return "X Speed";
        case Gen2Items::X_SPECIAL: return "X Special";
        case Gen2Items::COIN_CASE: return "Coin Case";
        case Gen2Items::ITEMFINDER: return "Itemfinder";
        case Gen2Items::TERU_SAMA5: return "Teru Sama 5";
        case Gen2Items::EXP_SHARE: return "Exp Share";
        case Gen2Items::OLD_ROD: return "Old Rod";
        case Gen2Items::GOOD_ROD: return "Good Rod";
        case Gen2Items::SILVER_LEAF: return "Silver Leaf";
        case Gen2Items::SUPER_ROD: return "Super Rod";
        case Gen2Items::PP_UP: return "PP Up";
        case Gen2Items::ETHER: return "Ether";
        case Gen2Items::MAX_ETHER: return "Max Ether";
        case Gen2Items::ELIXER: return "Elixer";
        case Gen2Items::RED_SCALE: return "Red Scale";
        case Gen2Items::SECRETPOTION: return "Secretpotion";
        case Gen2Items::SS_TICKET: return "SS Ticket";
        case Gen2Items::MYSTERY_EGG: return "Mystery Egg";
        case Gen2Items::CLEAR_BELL: return "Clear Bell";
        case Gen2Items::SILVER_WING: return "Silver Wing";
        case Gen2Items::MOOMOO_MILK: return "Moomoo Milk";
        case Gen2Items::QUICK_CLAW: return "Quick Claw";
        case Gen2Items::PSNCUREBERRY: return "Psncureberry";
        case Gen2Items::GOLD_LEAF: return "Gold Leaf";
        case Gen2Items::SOFT_SAND: return "Soft Sand";
        case Gen2Items::SHARP_BREAK: return "Sharp Break";
        case Gen2Items::PRZCUREBERRY: return "Przcureberry";
        case Gen2Items::BURNT_BERRY: return "Burnt Berry";
        case Gen2Items::ICE_BERRY: return "Ice Berry";
        case Gen2Items::POISON_BARB: return "Poison Barb";
        case Gen2Items::KINGS_ROCK: return "King's Rock";
        case Gen2Items::BITTER_BERRY: return "Bitter Berry";
        case Gen2Items::MINT_BERRY: return "Mint Berry";
        case Gen2Items::RED_APRICORN: return "Red Apricorn";
        case Gen2Items::TINYMUSHROOM: return "Tiny Mushroom";
        case Gen2Items::BIG_MUSHROOM: return "Big Mushroom";
        case Gen2Items::SILVERPOWDER: return "Silverpowder";
        case Gen2Items::BLU_APRICORN: return "Blu Apricorn";
        case Gen2Items::TERU_SAMA6: return "Teru Sama 6";
        case Gen2Items::AMULET_COIN: return "Amulet Coin";
        case Gen2Items::YLW_APRICORN: return "Ylw Apricorn";
        case Gen2Items::GRN_APRICORN: return "Grn Apricorn";
        case Gen2Items::CLEANSE_TAG: return "Cleanse Tag";
        case Gen2Items::MYSTIC_WATER: return "Mystic Water";
        case Gen2Items::TWISTEDSPOON: return "Twistedspoon";
        case Gen2Items::WHT_APRICORN: return "Wht Apricorn";
        case Gen2Items::BLACKBELT: return "Blackbelt";
        case Gen2Items::BLK_APRICORN: return "Blk Apricorn";
        case Gen2Items::TERU_SAMA7: return "Teru Sama 7";
        case Gen2Items::PNK_APRICORN: return "Pnk Apricorn";
        case Gen2Items::BLACKGLASSES: return "Blackglasses";
        case Gen2Items::SLOWPOKETAIL: return "Slowpoketail";
        case Gen2Items::PINK_BOW: return "Pink Bow";
        case Gen2Items::STICK: return "Stick";
        case Gen2Items::SMOKE_BALL: return "Smoke Ball";
        case Gen2Items::NEVERMELTICE: return "Nevermeltice";
        case Gen2Items::MAGNET: return "Magnet";
        case Gen2Items::MIRACLEBERRY: return "Miracleberry";
        case Gen2Items::PEARL: return "Pearl";
        case Gen2Items::BIG_PEARL: return "Big Pearl";
        case Gen2Items::EVERSTONE: return "Everstone";
        case Gen2Items::SPELL_TAG: return "Spell Tag";
        case Gen2Items::RAGECANDYBAR: return "Ragecandybar";
        case Gen2Items::GS_BALL: return "GS Ball";
        case Gen2Items::BLUE_CARD: return "Blue Card";
        case Gen2Items::MIRACLE_SEED: return "Miracle Seed";
        case Gen2Items::THICK_CLUB: return "Thick Club";
        case Gen2Items::FOCUS_BAND: return "Focus Band";
        case Gen2Items::TERU_SAMA8: return "Teru Sama 8";
        case Gen2Items::ENERGYPOWDER: return "Energypowder";
        case Gen2Items::ENERGY_ROOT: return "Energy Root";
        case Gen2Items::HEAL_POWDER: return "Heal Powder";
        case Gen2Items::REVIVAL_HERB: return "Revival Herb";
        case Gen2Items::HARD_STONE: return "Hard Stone";
        case Gen2Items::LUCKY_EGG: return "Lucky Egg";
        case Gen2Items::CARD_KEY: return "Card Key";
        case Gen2Items::MACHINE_PART: return "Machine Part";
        case Gen2Items::EGG_TICKET: return "Egg Ticket";
        case Gen2Items::LOST_ITEM: return "Lost Item";
        case Gen2Items::STARDUST: return "Stardust";
        case Gen2Items::STAR_PIECE: return "Star Piece";
        case Gen2Items::BASEMENT_KEY: return "Basement Key";
        case Gen2Items::PASS: return "Pass";
        case Gen2Items::TERU_SAMA9: return "Teru Sama 9";
        case Gen2Items::TERU_SAMAA: return "Teru Sama A";
        case Gen2Items::TERU_SAMAB: return "Teru Sama B";
        case Gen2Items::CHARCOAL: return "Charcoal";
        case Gen2Items::BERRY_JUICE: return "Berry Juice";
        case Gen2Items::SCOPE_LENS: return "Scope Lens";
        case Gen2Items::TERU_SAMAC: return "Teru Sama C";
        case Gen2Items::TERU_SAMAD: return "Teru Sama D";
        case Gen2Items::METAL_COAT: return "Metal Coat";
        case Gen2Items::DRAGON_FANG: return "Dragon Fang";
        case Gen2Items::TERU_SAMAE: return "Teru Sama E";
        case Gen2Items::LEFTOVERS: return "Leftovers";
        case Gen2Items::TERU_SAMAF: return "Teru Sama F";
        case Gen2Items::TERU_SAMA10: return "Teru Sama 10";
        case Gen2Items::TERU_SAMA11: return "Teru Sama 11";
        case Gen2Items::MYSTERYBERRY: return "Mysteryberry";
        case Gen2Items::DRAGON_SCALE: return "Dragon Scale";
        case Gen2Items::BERSERK_GENE: return "Berserk Gene";
        case Gen2Items::TERU_SAMA12: return "Teru Sama 12";
        case Gen2Items::TERU_SAMA13: return "Teru Sama 13";
        case Gen2Items::TERU_SAMA14: return "Teru Sama 14";
        case Gen2Items::SACRED_ASH: return "Sacred Ash";
        case Gen2Items::HEAVY_BALL: return "Heavy Ball";
        case Gen2Items::FLOWER_MAIL: return "Flower Mail";
        case Gen2Items::LEVEL_BALL: return "Level Ball";
        case Gen2Items::LURE_BALL: return "Lure Ball";
        case Gen2Items::FAST_BALL: return "Fast Ball";
        case Gen2Items::TERU_SAMA15: return "Teru Sama 15";
        case Gen2Items::LIGHT_BALL: return "Light Ball";
        case Gen2Items::FRIEND_BALL: return "Friend Ball";
        case Gen2Items::MOON_BALL: return "Moon Ball";
        case Gen2Items::LOVE_BALL: return "Love Ball";
        case Gen2Items::NORMAL_BOX: return "Normal Box";
        case Gen2Items::GORGEOUS_BOX: return "Gorgeous Box";
        case Gen2Items::SUN_STONE: return "Sun Stone";
        case Gen2Items::POLKADOT_BOW: return "Polkadot Bow";
        case Gen2Items::TERU_SAMA16: return "Teru Sama 16";
        case Gen2Items::UP_GRADE: return "Up Grade";
        case Gen2Items::BERRY: return "Berry";
        case Gen2Items::GOLD_BERRY: return "Gold Berry";
        case Gen2Items::SQUIRTBOTTLE: return "Squirtbottle";
        case Gen2Items::TERU_SAMA17: return "Teru Sama 17";
        case Gen2Items::PARK_BALL: return "Park Ball";
        case Gen2Items::RAINBOW_WING: return "Rainbow Wing";
        case Gen2Items::TERU_SAMA18: return "Teru Sama 18";
        case Gen2Items::BRICK_PIECE: return "Brick Piece";
        case Gen2Items::SURF_MAIL: return "Surf Mail";
        case Gen2Items::LITEBLUEMAIL: return "Litebluemail";
        case Gen2Items::PORTRAITMAIL: return "Portraitmail";
        case Gen2Items::LOVELY_MAIL: return "Lovely Mail";
        case Gen2Items::EON_MAIL: return "Eon Mail";
        case Gen2Items::MORPH_MAIL: return "Morph Mail";
        case Gen2Items::BLUESKY_MAIL: return "Bluesky Mail";
        case Gen2Items::MUSIC_MAIL: return "Music Mail";
        case Gen2Items::MIRAGE_MAIL: return "Mirage Mail";
        case Gen2Items::TERU_SAMA19: return "Teru Sama 19";
        case Gen2Items::TM01: return "TM01";
        case Gen2Items::TM02: return "TM02";
        case Gen2Items::TM03: return "TM03";
        case Gen2Items::TM04: return "TM04";
        case Gen2Items::TM04_2: return "TM04 2";
        case Gen2Items::TM05: return "TM05";
        case Gen2Items::TM06: return "TM06";
        case Gen2Items::TM07: return "TM07";
        case Gen2Items::TM08: return "TM08";
        case Gen2Items::TM09: return "TM09";
        case Gen2Items::TM10: return "TM10";
        case Gen2Items::TM11: return "TM11";
        case Gen2Items::TM12: return "TM12";
        case Gen2Items::TM13: return "TM13";
        case Gen2Items::TM14: return "TM14";
        case Gen2Items::TM15: return "TM15";
        case Gen2Items::TM16: return "TM16";
        case Gen2Items::TM17: return "TM17";
        case Gen2Items::TM18: return "TM18";
        case Gen2Items::TM19: return "TM19";
        case Gen2Items::TM20: return "TM20";
        case Gen2Items::TM21: return "TM21";
        case Gen2Items::TM22: return "TM22";
        case Gen2Items::TM23: return "TM23";
        case Gen2Items::TM24: return "TM24";
        case Gen2Items::TM25: return "TM25";
        case Gen2Items::TM26: return "TM26";
        case Gen2Items::TM27: return "TM27";
        case Gen2Items::TM28: return "TM28";
        case Gen2Items::TM28_2: return "TM28 2";
        case Gen2Items::TM29: return "TM29";
        case Gen2Items::TM30: return "TM30";
        case Gen2Items::TM31: return "TM31";
        case Gen2Items::TM32: return "TM32";
        case Gen2Items::TM33: return "TM33";
        case Gen2Items::TM34: return "TM34";
        case Gen2Items::TM35: return "TM35";
        case Gen2Items::TM36: return "TM36";
        case Gen2Items::TM37: return "TM37";
        case Gen2Items::TM38: return "TM38";
        case Gen2Items::TM39: return "TM39";
        case Gen2Items::TM40: return "TM40";
        case Gen2Items::TM41: return "TM41";
        case Gen2Items::TM42: return "TM42";
        case Gen2Items::TM43: return "TM43";
        case Gen2Items::TM44: return "TM44";
        case Gen2Items::TM45: return "TM45";
        case Gen2Items::TM46: return "TM46";
        case Gen2Items::TM47: return "TM47";
        case Gen2Items::TM48: return "TM48";
        case Gen2Items::TM49: return "TM49";
        case Gen2Items::TM50: return "TM50";
        case Gen2Items::HM01: return "HM01";
        case Gen2Items::HM02: return "HM02";
        case Gen2Items::HM03: return "HM03";
        case Gen2Items::HM04: return "HM04";
        case Gen2Items::HM05: return "HM05";
        case Gen2Items::HM06: return "HM06";
        case Gen2Items::HM07: return "HM07";
        case Gen2Items::HM08: return "HM08";
        case Gen2Items::HM09: return "HM09";
        case Gen2Items::HM10: return "HM10";
        case Gen2Items::HM11: return "HM11";
        case Gen2Items::HM12: return "HM12";
        default: return "Unknown Item";
    }
}

const char* getGen2DecorationString(Gen2Decoration decoration)
{
    switch (decoration)
    {
        case Gen2Decoration::FEATHERY_BED: return "Feathery Bed";
        case Gen2Decoration::PINK_BED: return "Pink Bed";
        case Gen2Decoration::POLKADOT_BED: return "Polkadot Bed";
        case Gen2Decoration::PIKACHU_BED: return "Pikachu Bed";
        case Gen2Decoration::RED_CARPET: return "Red Carpet";
        case Gen2Decoration::BLUE_CARPET: return "Blue Carpet";
        case Gen2Decoration::YELLOW_CARPET: return "Yellow Carpet";
        case Gen2Decoration::GREEN_CARPET: return "Green Carpet";
        case Gen2Decoration::MAGNAPLANT: return "Magnaplant";
        case Gen2Decoration::TROPICPLANT: return "Tropicplant";
        case Gen2Decoration::JUMBOPLANT: return "Jumboplant";
        case Gen2Decoration::TOWN_MAP: return "Town Map";
        case Gen2Decoration::PIKACHU_POSTER: return "Pikachu Poster";
        case Gen2Decoration::CLEFAIRY_POSTER: return "Clefairy Poster";
        case Gen2Decoration::JIGGLYPUFF_POSTER: return "Jigglypuff Poster";
        case Gen2Decoration::NES: return "NES";
        case Gen2Decoration::SUPER_NES: return "Super NES";
        case Gen2Decoration::NINTENDO_64: return "Nintendo 64";
        case Gen2Decoration::VIRTUAL_BOY: return "Virtual Boy";
        case Gen2Decoration::BIG_SNORLAX: return "Big Snorlax";
        case Gen2Decoration::BIG_ONIX: return "Big Onix";
        case Gen2Decoration::BIG_LAPRAS: return "Big Lapras";
        case Gen2Decoration::PIKACHU_DOLL: return "Pikachu Doll";
        case Gen2Decoration::SURF_PIKACHU_DOLL: return "Surf Pikachu Doll";
        case Gen2Decoration::CLEFAIRY_DOLL: return "Clefairy Doll";
        case Gen2Decoration::JIGGLYPUFF_DOLL: return "Jigglypuff Doll";
        case Gen2Decoration::BULBASAUR_DOLL: return "Bulbasaur Doll";
        case Gen2Decoration::CHARMANDER_DOLL: return "Charmander Doll";
        case Gen2Decoration::SQUIRTLE_DOLL: return "Squirtle Doll";
        case Gen2Decoration::POLIWAG_DOLL: return "Poliwag Doll";
        case Gen2Decoration::DIGLETT_DOLL: return "Diglett Doll";
        case Gen2Decoration::STARYU_DOLL: return "Staryu Doll";
        case Gen2Decoration::MAGIKARP_DOLL: return "Magikarp Doll";
        case Gen2Decoration::ODDISH_DOLL: return "Oddish Doll";
        case Gen2Decoration::GENGAR_DOLL: return "Gengar Doll";
        case Gen2Decoration::SHELLDER_DOLL: return "Shellder Doll";
        case Gen2Decoration::GRIMER_DOLL: return "Grimer Doll";
        case Gen2Decoration::VOLTORB_DOLL: return "Voltorb Doll";
        case Gen2Decoration::WEEDLE_DOLL: return "Weedle Doll";
        case Gen2Decoration::UNOWN_DOLL: return "Unown Doll";
        case Gen2Decoration::GEODUDE_DOLL: return "Geodude Doll";
        case Gen2Decoration::MACHOP_DOLL: return "Machop Doll";
        case Gen2Decoration::TENTACOOL_DOLL: return "Tentacool Doll";
        case Gen2Decoration::GOLD_TROPHY: return "Gold Trophy";
        case Gen2Decoration::SILVER_TROPHY: return "Silver Trophy";
        default: return "Unknown Decoration";
    }
}